CREATE TABLE STUDENTS (
  STUDENT_ID             INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
  STUDENT_FIRSTNAME       VARCHAR(40),
  STUDENT_LASTNAME        VARCHAR(40),
  LOGIN                   VARCHAR(40),
  PASSWORD                VARCHAR(40),
CONSTRAINT PK_STUDENTS PRIMARY KEY (STUDENT_ID)
)
;

CREATE TABLE TUTORS (
  TUTOR_ID                INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
  TUTOR_FIRSTNAME         VARCHAR(40),
  TUTOR_LASTNAME          VARCHAR(40),
  LOGIN                   VARCHAR(40),
  PASSWORD                VARCHAR(40),
CONSTRAINT PK_TUTORS PRIMARY KEY (TUTOR_ID)
)
;

CREATE TABLE STUDENT_COURSE (
  STUDENT_ID              INT(10) ZEROFILL NOT NULL,
  COURSE_ID               INT(10) ZEROFILL NOT NULL,
  MARK                    INT(3),
  FEEDBACK                VARCHAR(200)
)
;

CREATE TABLE COURSES (
  COURSE_ID               INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
  COURSE_NAME             VARCHAR(40),
  TUTOR_ID                INT(10) NOT NULL,
  STARTING_DATE           DATE,
  FINISHING_DATE          DATE,
  ACTIVE                  BOOLEAN,
CONSTRAINT PK_COURSES PRIMARY KEY (COURSE_ID)
)
;

ALTER TABLE STUDENT_COURSE
    ADD CONSTRAINT One_Course_To_Many_Student_Courses
        FOREIGN KEY (COURSE_ID)
            REFERENCES COURSES (COURSE_ID)
 ;

ALTER TABLE STUDENT_COURSE
    ADD CONSTRAINT One_Student_To_Many_Student_Courses
        FOREIGN KEY (STUDENT_ID)
            REFERENCES STUDENTS (STUDENT_ID)
 ;


ALTER TABLE COURSES
    ADD CONSTRAINT One_Tutor_To_One_Course
        FOREIGN KEY (TUTOR_ID)
            REFERENCES TUTORS (TUTOR_ID)
 ;
