/*STUDENTS*/
INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (0,'LAURA','HIEME','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (1,'SAM','GARRISON','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (2,'DONALD','TRUMP','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (3,'LESLEY','DOWNER','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (4,'KEN','HAM','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (5,'JESSE','LESNER','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (6,'CASTER','DOUCHE','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (7,'MAY','LE SOUGE','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (8,'BOB','FONTAINE','0','0');

INSERT INTO STUDENTS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (9,'SAID','AL-MAIJD','0','0');

/*TUTORS*/
INSERT INTO TUTORS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (0,'HUE','CHONG','0','0');

INSERT INTO TUTORS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (1,'GAVIN','KENSEY','0','0');

INSERT INTO TUTORS (STUDENT_ID,STUDENT_FIRSTNAME,STUDENT_LASTNAME,LOGIN,PASSWORD)
VALUES (2,'ANTON','PETROV','0','0');

/*COURSES*/
INSERT INTO COURSES ( COURSE_ID,
  COURSE_NAME           ,
  TUTOR_ID              ,
  STARTING_DATE         ,
  FINISHING_DATE        ,
  ACTIVE                )
VALUES ( 0,
'COURSE_1',
0,
17-DEC-2018,
18-DEC-2018,
TRUE
);

INSERT INTO COURSES ( COURSE_ID,
  COURSE_NAME           ,
  TUTOR_ID              ,
  STARTING_DATE         ,
  FINISHING_DATE        ,
  ACTIVE                )
VALUES ( 1,
'COURSE_2',
2,
1-DEC-2018,
8-DEC-2018,
FALSE
);

/*STUDENT COURSE*/
INSERT INTO STUDENT_COURSE (STUDENT_ID,
  COURSE_ID,
  MARK,
  FEEDBACK
  )
VALUES ( 0,
0,
NULL,
''
)






